ttt-build: memory.cpp MemoryFitnessCalculator.cpp MemoryAgent.cpp MemoryFitnessCalculator.cpp MemoryAgentFactory.cpp
	g++ -o memory $^ -L../../build/. -lai -std=c++11 -O3

memory:
	rm -f memory

all: memory

clean: memory

